language: c
os:
  - windows
  - linux
  - osx

addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - p7zip-full
  choco:
    packages:
      - make
 
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap PX4/homebrew-px4 && brew update && brew install gcc-arm-none-eabi-48; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget https://sourceforge.net/projects/yagarto/files/YAGARTO%20for%20Windows/20111119/yagarto-bu-2.21_gcc-4.6.2-c-c%2B%2B_nl-1.19.0_gdb-7.3.1_eabi_20111119.exe; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 7z x "yagarto-bu-2.21_gcc-4.6.2-c-c++_nl-1.19.0_gdb-7.3.1_eabi_20111119.exe" -oyagarto; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH="$PWD/yagarto/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi
script:
  - make
before_deploy:
  - 7z a boot-$TRAVIS_OS_NAME.zip boot.*
deploy:
  provider: releases
  api_key:
    secure: LCcxsPbC+j8hVWiY+OIrlcMQVGIkNzfoLzIHh5wXIrSTy7ngmXnXR90MwaKA3KUvpHaTQprFLn71G6m413meJeiQOgIo4Vaz4w+i/ADgPjc066TiTGmXtbGs27l4KBBlXNaQbVrbkAVTHJFbHFgl4z6kjUW5lGl+utYY94ygBB2JceHjGbTcZkyEE5i3R3DFDHjz/J4f/91lv15vuRisk2quEzMowFIskNdZ9XnY2AKi2OTJSAo0T/M7m9HCeor5ctzKQkSN0kocbCko7zHLilu5hzvPryOm86U3fhBqqoBB2kpaTnpwfRZuc3sVfjd5//JaCzISnwx81auGo+rSmkyrrtFv7Du2Ivt84CCuy6dXgTBiFI/1OiojIWME2PIrcIibDO+gRtE0ZUkOM1PX7SMSNdNSSZbxrp2ZeAHHB1WdIZ049ZsGT6FUuz+Y8GbwuImB7aDs3zKjVY1IN0CziMuMsDh8lhVA5OBJw7x+S5UUhAXQcNmS+gr4E/iATmqqt3AL/oC310nf5sEwwUkMAR1A5JlKcQFbgAnBMMx4G8DFfy1bsAxhUb3BgaLQ5Sg0GjFjWWuwFPvHqLikSclJFeZe86ZoUoUg3DbLgZfha2/OnjfIgIo3hrGNYXK3lu/PJmkxDZHPue2n/Ky9xNMIALXprrOw1GNBVralNPk2BIw=
  file_glob: true
  file: boot-$TRAVIS_OS_NAME.zip
  skip_cleanup: true
#  draft: true
  overwrite: true
  on:
    repo: erique/yagarto-build
    branch: master
    tags: true
